import Header from "@/components/layout/header";
import "./globals.css";
import { Rubik } from "next/font/google";
import Footer from "@/components/layout/footer";
import FixedNavbar from "@/components/layout/fixedNavbar";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  weight: "300",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <Header />
        {children}
        <Footer />
        <div className="text-center py-10 md:block hidden">
          &copy; 2021 Elemes id. All rights reserved
        </div>
        <FixedNavbar />
      </body>
    </html>
  );
}
